### POST request to create a New Patient Record
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Leni Yoro",
  "email": "Yoro.Leni@example.com",
  "address": "House 12 Madrid Spain",
  "dateOfBirth": "1982-12-19",
  "registeredDate": "2025-10-23"
}

###