### POST request to create a New Patient Record
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Patrick Dorgu",
  "email": "dorgu.patrick@example.com",
  "address": "House 143 Carrington UK",
  "dateOfBirth": "2000-12-19",
  "registeredDate": "2025-10-15"
}

###